Repository meyer1994/regular, pull requests merged in 2018-06, with the labels that each got.

#23 Modified Union function
  src/nfa.js
  test/test_nfa.js
Labels: bug

#24 Implemented enumerate function
  src/grammar.js
  test/test_grammar.js
Labels: enhancement

#26 Fixed bug in enumerate function and added some more tests
  src/grammar.js
  src/nfa.js
  test/test_grammar.js
  test/test_nfa.js
Labels: bug, enhancement

#29 Created github page
  index.html
  interface/grammar.js
  interface/nfa.js
  interface/re.js
Labels: enhancement

#34 Fixed major bugs in user interface and functions ...
  interface/grammar.js
  interface/inputs.js
  interface/nfa.js
  src/grammar.js
  src/nfa.js
  test/test_grammar.js
  test/test_nfa.js
Labels: bug

#35 Fixed bug in operations component;
  interface/inputs.js
Labels: bug

#37 Reverting..
  interface/inputs.js
Labels: bug
